apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cool-tour-app-ingress
  namespace: cool-tour
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/affinity: "cookie"                    # Enable sticky sessions
    nginx.ingress.kubernetes.io/session-cookie-name: "route"           # Session cookie name for sticky sessions
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"            # Hashing method for sticky sessions
    nginx.ingress.kubernetes.io/secure-backends: "true"                # Secure backend communication
spec:
  rules:
    - host: cooltour.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cool-tour-app-service
                port:
                  number: 80
