apiVersion: apps/v1
kind: Deployment
metadata:
  name: cool-tour-app-deployment
  namespace: cool-tour
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cool-tour-app
  template:
    metadata:
      labels:
        app: cool-tour-app
    spec:
      initContainers:
        - name: init-db
          image: postgres:16
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: cool-tour-app-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: cool-tour-app-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cool-tour-app-secret
          command: ['sh', '-c', 'PGPASSWORD=$POSTGRES_PASSWORD psql -h cool-tour-postgres-service -U $POSTGRES_USER -d $POSTGRES_DB -f /init/init.sql']
          volumeMounts:
            - mountPath: /init
              name: init-scripts
      containers:
        - name: cool-tour
          image: vlade25/cool-tour:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: cool-tour-app-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cool-tour-app-secret
      volumes:
        - name: init-scripts
          configMap:
            name: init-scripts